var data = [
  { "manufacturer" : "Samsung",
	"model" : "Galaxy S7 Edge",
	"price" : "510$",
	"color" : "Grey",
	
  },
  { "manufacturer" : "Apple",
	"model" : "iPhone 7 32GB",
	"price" : "820$",
	"color" : "Black",
  },
  { "manufacturer" : "Samsung",
	"model" : "Galaxy J7",
	"price" : "240$",
	"color" : "Grey",
  },
  { "manufacturer" : "Huawei",
	"model" : "P9",
	"price" : "400$",
	"color" : "Rose gold",
  },
  { "manufacturer" : "Nexus",
	"model" : "5",
	"price" : "300$",
	"color" : "White",
  }
];